variables:
    PYPI_USER: SECURE
    PYPI_PASSWORD: SECURE
    PYTHONUNBUFFERED: 1

cache:
  paths:
    - .coverage
    - reports

stages:
  - test
  - coverage
  - live_tests
  - deploy
  - cleanup

python_2_7:
   stage: test
   image: python:2.7
   script:
     - apt-get update -qy
     - apt-get install -y python-pip
     - pip install -r tests/requirements.txt
     - conan user
     - mkdir ~/.conan/data  # This directory is not generated on install
     - py.test --cov=conan_sword_and_sorcery tests/  # Run with coverage (but do not store)
   except:
     - /^notest/

python_3_6:
   stage: test
   image: python:3.6
   script:
     - apt-get update -qy
     - apt-get install -y python-pip
     - pip install -r tests/requirements.txt
     - conan user
     - mkdir ~/.conan/data  # This directory is not generated on install
     - py.test --cov=conan_sword_and_sorcery --cov-report=html:reports/html tests/  # Run with coverage
   except:
     - /^notest/
   artifacts:
     paths:
      - .coverage
      - reports

coverage:
  stage: coverage
  image: python:3.6
  script:
    - pip -q install coverage
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  dependencies:
    - python_2_7
    - python_3_6
  except:
    - /^notest/


gcc_49_all:
   stage: live_tests
   image: lasote/conangcc49
   script:
     - sudo pip install .
     - conan user
     - TRAVIS=true TRAVIS_BRANCH=testing CONAN_GCC_VERSIONS=4.9 run_ci tests/files/example1/conanfile.py
   except:
     - /^notest/

gcc_49_x86_release,option1:
   stage: live_tests
   image: lasote/conangcc49
   script:
     - sudo pip install .
     - conan user
     - TRAVIS=true TRAVIS_BRANCH=testing CONAN_GCC_VERSIONS=4.9 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_OPTIONS=option1 run_ci tests/files/example1/conanfile.py
   except:
     - /^notest/

clang_50_release:
   stage: live_tests
   image: lasote/conanclang50
   script:
     - sudo pip install .
     - conan user
     - TRAVIS=true TRAVIS_BRANCH=testing CONAN_CLANG_VERSIONS=4.9 CONAN_ARCHS=x86,x86_64 CONAN_BUILD_TYPES=Release run_ci tests/files/example1/conanfile.py
   except:
     - /^notest/

gcc_49_dockerized:
   stage: live_tests
   image: python:3.6
   services:
     - docker
   script:
     - sudo pip install .
     - conan user
     - sudo apt-get update
     - sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
     - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
     - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     - sudo apt-get update
     - sudo apt-get install docker-ce
     - TRAVIS=true TRAVIS_BRANCH=testing CONAN_GCC_VERSIONS=4.9 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conangcc49 run_ci tests/files/example1/conanfile.py
   except:
     - /^notest/

deploy_pypi:
  stage: deploy
  image: python:3.6
  script:   # Configure the PyPI credentials, then push the package, and cleanup the creds.
    - pip -q install twine
    - rm -rf dist
    - echo "[distutils]" >> ~/.pypirc
    - echo "index-servers =" >> ~/.pypirc
    - echo "    pypi" >> ~/.pypirc
    - echo "" >> ~/.pypirc
    - echo "[pypi]" >> ~/.pypirc
    - echo "${PYPI_REPO}" >> ~/.pypirc
    - echo "${PYPI_USER}" >> ~/.pypirc
    - echo "${PYPI_PASSWORD}" >> ~/.pypirc
    - python3 setup.py check sdist # bdist (copy only source distribution)
    - twine upload -r pypi dist/*  # Uses env variables TWINE_USERNAME and TWINE_PASSWORD
  only:
    - /^v(\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?$/  # PEP-440 compliant version (with 'v' at the beginning)
  except:
    - branches


pages:
  stage: deploy
  dependencies:
    - python_3_6
  script:
    - mv reports/html public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master


cleanup_pypirc:
   stage: cleanup
   when: always   # this is important; run even if preceding stages failed.
   script:
    - rm -vf ~/.pypirc  # we don't want to leave these around, but GitLab may clean up anyway.
   only:
    - /^v(\d+!)?(\d+)(\.\d+)+([\.\-\_])?((a(lpha)?|b(eta)?|c|r(c|ev)?|pre(view)?)\d*)?(\.?(post|dev)\d*)?$/  # PEP-440 compliant version (with 'v' at the beginning)
   except:
    - branches

